### ISSUE TITLE
[SR-15020] swift test fails on macOS without Xcode

### ISSUE THREAD

**Issue by 0xTim** [swiftlang/swift-package-manager#4396]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15020      |
   |Radar             | rdar://problem/81575974         |
   |Original Reporter | @0xTim      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Package Manager    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 0beac16b14a45b66909ff8f25fe2b6b5

  </details>

**Issue Description:**

When attempting to run `swift test` on a package on macOS without Xcode installed, it fails because it can't find the Objective-C runtime.

 

`swift test` should use the inbuilt test discovery for finding tests so behaviour of Swift is consistent across all platforms. (Note this should not affect running tests in Xcode as this can still use the Obj-C runtime

**Comment by Kikishen01** [comment]
> Having the option to run the xctest solution used by Linux and Windows on macOS would simplify a number of things for the Visual Studio Code Swift extension.
> 
> As a starter it would resolve [SR-15997](https://bugs.swift.org/browse/SR-15997)

**Comment by Kikishen01** [comment]
> Having the option to run the xctest solution used by Linux and Windows on macOS would simplify a number of things for the Visual Studio Code Swift extension.
> 
> As a starter it would resolve [SR-15997](https://bugs.swift.org/browse/SR-15997)

**Comment by Mdsohan782** [comment]
423400

**Comment by apps4everyone** [comment]
any news here?

**Comment by 0xTim** [comment]
I think the answer is probably https://github.com/apple/swift-testing because that can be pulled in via a package and not reliant on the Obj-C runtime being installed

**Comment by grynspan** [comment]
As of the current main-branch Swift toolchain, it should be possible to run tests using Swift Testing without needing to install Xcode first (we're still working on the fine details.) I'd recommend you take a look at Swift Testing if you need to run tests on macOS without installing Xcode first.

Xcode and the Xcode Command Line Tools package are proprietary Apple software and, as such, are not part of the Swift open source project. XCTest, as included with Xcode, is also proprietary and is not available without installing Xcode.
