### ISSUE TITLE
[SR-14892] handle directories with dots in their names

### ISSUE THREAD

**Issue by amomchilov** [swiftlang/swift-package-manager#4405]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-14892      |
   |Radar             | rdar://problem/80278112         |
   |Original Reporter | @amomchilov      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | Package Manager    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 72d2e6348eaa1cc7b492dfbcc69ac85d

  </details>

**Issue Description:**

Say I have a folder with one or more periods in its name, such as `foo.bar`. Currently, SPM sees this as a a `.bar` bundle and forces me to either list it as a resource, or to exclude it from my target.

Is there any way to make SPM "leave it alone" and just treat it as a regular old directory? I want the files within it to be treated as normal. E.g. asset catalogs are picked up as resources, `.swift` files are picked up as sources, etc.

For background:

-   On macOS, a folder with a directory in its name will be treated as a bundle only if there's a registered UTI that conforms to `com.apple.bundle` which is associated with that filename extension. Even still, bundles are really just directories, and you can still browse their contents.

-   On Linux, dots in folder names have no special significance, and there is no "bundle" concept, at all!

Forum thread: <https://forums.swift.org/t/supporting-folders-with-dots-in-their-names/50251>

**Comment by MaxDesiatov** [comment]
This is not reproducible with 6.0 snapshots.
