### ISSUE TITLE
[SR-14885] Expose test discovery list

### ISSUE THREAD

**Issue by 0xTim** [swiftlang/swift-package-manager#4406]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-14885      |
   |Radar             | rdar://problem/80267816         |
   |Original Reporter | @0xTim      |
   |Type              | New Feature    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | Package Manager    |
   |Labels            | New Feature        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 4ada4510db1d451aab741ce5d783fe40

  </details>

**Issue Description:**

In order for certain test integrations to work in other IDEs and on Linux it would be extremely helpful for SwiftPM to expose the list of tests it can see via test discovery so they can be displayed in VSCode's Test Explorer for example.

 

Something like `swift package list-tests` which outputs a JSON blob would be great.

**Comment by grynspan** [comment]
`swift test list` is what VSCode uses today, I believe? That, or SourceKit-LSP, would be the correct mechanism for enumerating XCTest-based tests.
