### ISSUE TITLE
[SR-13946] Can't generate tests for Swift 5.0 on Linux: generate-linuxmain is deprecated and a no-op

### ISSUE THREAD

**Issue by glbrntt** [swiftlang/swift-package-manager#4461]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13946      |
   |Radar             | rdar://problem/72160848         |
   |Original Reporter | @glbrntt      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Package Manager    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 08b7e06a218c7018cc6eae816f4b1730

  </details>

**Issue Description:**

swift test --generate-linuxmain recently started emitting a warning that it is deprecated and it no longer generates the test manifests for Linux.

Deprecating it absolutely makes sense given that test discovery has been available on Linux since 5.1.

However, removing the functionality to generate the manifests is awkward for library maintainers who still support Swift 5.0 on Linux: our options at the moment (as far as I see) are to keep an old enough toolchain around just for generating manifests or switch to scripts which parse the test code to generate manifests; neither of which are great solutions.

Ideally the functionality would be restored (while keeping the deprecation warning) until the next major version of Swift.

**Comment by grynspan** [comment]
`--generate-linuxmain` has been removed and is no longer supported. Not planning to add it back at this stage. (Sorry I'm quite late in replying here!)
