### ISSUE TITLE
[SR-13718] `swift test --generate-linuxmain` doesn't grok conditionally compiled tests

### ISSUE THREAD

**Issue by lorentey** [swiftlang/swift-package-manager#4488]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13718      |
   |Radar             | rdar://problem/70268548         |
   |Original Reporter | @lorentey      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164963983-c72f51a1-b448-4da9-955a-56b00139a94b.gz)

      
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Package Manager    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 376ee6032ad73b2b9443fab165a3646a

  </details>

**Issue Description:**

The swift-atomics package has some functionality that may be unavailable depending on properties of the underlying architecture. In particular, atomic strong references are only available when the target platform supports double-wide atomic primitives. Linux happens to prevent the use of double-wide atomics on x86_64 by default, so these features aren't normally available there.

This means that XCTestCase classes that test this functionality must be placed behind a compile-time \`#if\` conditional.

Unfortunately SwiftPM's handy \`swift test --generate-linuxmain\` functionality ignores conditional compilation directives, and unconditionally tries to register all tests, leading to a broken test manifest.

To reproduce, download the attached sample package and try to build its test on Linux.

    // fooTests.swift
    import XCTest
    @testable import foo

    #if !(os(Linux) && arch(x86_64)) || ENABLE_FOO
    final class fooTests: XCTestCase {
        func testExample() {
            // This is an example of a functional test case.
            // Use XCTAssert and related functions to verify your tests produce the correct
            // results.
            XCTAssertEqual(foo().text, "Hello, World!")
        }

        static var allTests = [
            ("testExample", testExample),
        ]
    }
    #endif

Generated XCTestManifests.swift:

    #if !canImport(ObjectiveC)
    import XCTest

    extension fooTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__fooTests = [
            ("testExample", testExample),
        ]
    }

    public func __allTests() -> [XCTestCaseEntry] {
        return [
            testCase(fooTests.__allTests__fooTests),
        ]
    }
    #endif

Output when attempting to build this on Ubuntu 20.04 with the Swift 5.3 toolchain:

    root@a7f9a25d4f88:/host/foo# swift test 
    /host/foo/Tests/fooTests/XCTestManifests.swift:4:11: error: cannot find type 'fooTests' in scope
    extension fooTests {
              ^
    /host/foo/Tests/fooTests/XCTestManifests.swift:4:11: note: cannot use module 'fooTests' as a type
    extension fooTests {
              ^
    /host/foo/Tests/fooTests/XCTestManifests.swift:15:18: error: module 'fooTests' has no member named '__allTests__fooTests'
            testCase(fooTests.__allTests__fooTests),
                     ^~~~~~~~ ~~~~~~~~~~~~~~~~~~~~
    /host/foo/Tests/fooTests/XCTestManifests.swift:9:25: error: cannot find 'testExample' in scope
            ("testExample", testExample),
                            ^~~~~~~~~~~

**Comment by grynspan** [comment]
`--generate-linuxmain` has been removed and is no longer supported.
