### ISSUE TITLE
[SR-12147] swiftpm-xctest-helper fails on XCTestCase using dynamic test generation

### ISSUE THREAD

**Issue by belkadan** [swiftlang/swift-package-manager#4609]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-12147      |
   |Radar             | rdar://problem/59280719         |
   |Original Reporter | @belkadan      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164963640-c8c1212a-bedc-4d9b-bd6e-75411a46807a.gz)

      
<details>
  <summary>Environment</summary>

Xcode 11.3.1

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Package Manager    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: aeff0ee827908e11f88cae54d5bd7f1c

  </details>

**Issue Description:**

When an XCTestCase subclass has a custom `name` (as is useful for dynamic test generation), and that name is not in the same format as a usual XCTest test case name (i.e. `"-[MyTests someSelector]"`), `swift test -l` just crashes. I've attached an example project (which you can also find [here](https://belkadan.com/source/ROSE-8/commit/6ba964352de647ceb0394a3d54e302a15f1e672f)) along with a crash log from Xcode 11.3.1.

I didn't test this on Linux because I'm generating the dynamic tests differently on Linux (due to differences in how test discovery works).

**Comment by grynspan** [comment]
The reported crash is specific to XCTest.framework in Xcode and is not part of the open source Swift project. Closing this GitHub issue; Apple will continue to track the corresponding radar. Thanks for filing!
