### ISSUE TITLE
[SR-12008] SwiftPM: On Linux, enable-test-discovery stumbles over deprecated tests

### ISSUE THREAD

**Issue by weissi** [swiftlang/swift-package-manager#4628]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-12008      |
   |Radar             | rdar://problem/58475855         |
   |Original Reporter | @weissi      |
   |Type              | Bug    |
   |Status            | In Progress        |
   |Resolution        |     |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 2         |
   |Component/s       | Package Manager    |
   |Labels            | Bug, Linux        |
   |Assignee          | 3a4oT (JIRA)      |
   |Priority          | Medium      |

   

   md5: fc60a1ed0f31111134228b7e176436d5

  </details>

**Issue Description:**

It's very important to also test deprecated functionality which on Darwin is easily possible by deprecating the test method. When manually generating LinuxMain and friends, this is also possible via a small [hack](https://github.com/apple/swift-nio/blob/master/scripts/generate_linux_tests.rb#L103-L111).

Repro:

    git clone https://github.com/apple/swift-nio
    cd swift-nio
    docker run -it --rm -v "$PWD:$PWD" -w "$PWD" swift:5.1.3 swift test -Xswiftc -warnings-as-errors --enable-test-discovery

Expected:

Runs the tests just fine like on Darwin or without `enable-test-discovery`

Actual:

many errors.

    /Users/johannes/devel/swift-nio/.build/x86_64-unknown-linux/debug/testlist.derived/NIOConcurrencyHelpersTests.swift:6:24: error: 'testAddSub()' is deprecated: deprecated because it tests deprecated functionality
            ("testAddSub", testAddSub),
                           ^
    /Users/johannes/devel/swift-nio/.build/x86_64-unknown-linux/debug/testlist.derived/NIOConcurrencyHelpersTests.swift:8:35: error: 'testAllOperationsBool()' is deprecated: deprecated because it tests deprecated functionality
            ("testAllOperationsBool", testAllOperationsBool),
                                      ^

**Comment by grynspan** [comment]
Duplicate of #3992
