### ISSUE TITLE
[SR-11951] Test discovery on Linux breaks with test class extensions in multiple files

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/swift-package-manager#4635]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-11951      |
   |Radar             | rdar://problem/58435666         |
   |Original Reporter | siemensikkema (JIRA User)      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164963578-ffbda7ad-f2dc-4297-b908-04e41de6ad04.gz)

      
<details>
  <summary>Environment</summary>

(Ubuntu) Linux

Docker image swift:5.1

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Package Manager, XCTest    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: c363235c1de0150b1ca7961dbfc9ed16

  </details>

**is duplicated by**:  
* [SR-11968](https://bugs.swift.org/browse/SR-11968) SwiftPM test discovery: creating extra tests in separate files causes build errors  
* [SR-14512](https://bugs.swift.org/browse/SR-14512) Duplicate __allTests__ array when extending a XCTestCase class on Linux  

**Issue Description:**

When having tests in an XCTestCase class in extensions in *multiple* files while using `--enable-test-discovery` building the test target fails with:

`[9/12] Compiling ExamplePackageTests ExampleTests.swift /package/.build/x86_64-unknown-linux/debug/testlist.derived/ExampleTests.swift:11:16: error: invalid redeclaration of '_allTests_ExampleTests' static let _allTestsExampleTests = [ ^ /package/.build/x86_64-unknown-linux/debug/testlist.derived/ExampleTests.swift:5:16: note: 'allTests_ExampleTests' previously declared here static let _allTests_ExampleTests = [`

The attached example can be run with `docker build .`

The example has a test in the class definition itself and one in an extension. But the problem also appears when having an empty class definition and tests in 2 or more extensions each in their own file.

**Comment by grynspan** [comment]
Fixed by #3433
