### ISSUE TITLE
[SR-11779] Error message for missing source files says files should be under 'Sources/Target' for test target

### ISSUE THREAD

**Issue by mdiep** [swiftlang/swift-package-manager#4650]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-11779      |
   |Radar             | rdar://problem/57163410         |
   |Original Reporter | @mdiep      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Apple Swift version 5.1.2 (swiftlang-1100.0.278 clang-1100.0.33.9)  
Target: x86_64-apple-darwin19.0.0

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Package Manager    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 4594355ffd7eb5c52db9c06ca4a692c5

  </details>

**Issue Description:**

``` java
» mkdir TestPM
» cd TestPM
» swift package init
» rm -rf Tests/TestPMTests
» swift build
'TestPM' TestPM: error: Source files for target TestPMTests should be located under 'Sources/TestPMTests', or a custom sources path can be set with the 'path' property in Package.swift
```

That error says the files should be under `Sources/TestPMTests`, but they should actually be under `Tests/TestPMTests`.

**Comment by grynspan** [comment]
Fixed by #6294

(As far as I can tell.)
