### ISSUE TITLE
[SR-5467] The .build/debug symlink doesn't work for SwiftPM development

### ISSUE THREAD

**Issue by hartbit** [swiftlang/swift-package-manager#4983]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-5467      |
   |Radar             | None         |
   |Original Reporter | @hartbit      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Package Manager    |
   |Labels            | Bug, StarterBug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 296f6ad61384e581dee3f17ac4f6cd47

  </details>

**relates to**:  
* [SR-5801](https://bugs.swift.org/browse/SR-5801) Inaccurate documentation of how to run swift-build  

**Issue Description:**

The reason is that SwiftPM will incorrectly expect to find the library folder at `.build/lib` but it's now in `.build/target/lib`. The bootstrap script should probably create a symlink.

**Comment by MaxDesiatov** [comment]
The bootstrapping code has changed significantly and I don't remember seeing this issues or anything related to it recently. Assuming it's fixed or outdated, feel free to reopen with repro steps otherwise.
