### ISSUE TITLE
[SR-4725] Support Test Collateral in Package Manager 

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/swift-package-manager#5030]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-4725      |
   |Radar             | None         |
   |Original Reporter | owensd (JIRA User)      |
   |Type              | New Feature    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 6         |
   |Component/s       | Package Manager    |
   |Labels            | New Feature        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: f1c9317e97dfd1c1578d379e97bc2a11

  </details>

**relates to**:  
* [SR-2866](https://bugs.swift.org/browse/SR-2866) [SwiftPM] Need a way to include resources with targets  

**Issue Description:**

The Swift Package Manager needs the ability to place test collateral in the output folder. Currently, I have to resort to this hack:

let path = NSString.path(withComponents: \[Bundle(for: JSValuePerformanceTests.self).bundlePath, "..", "..", "..", "TestCollateral", "sample.json"\])

**Comment by grynspan** [comment]
`Bundle.package` ought to be the right tool for this sort of job.

Closing this issue with the recommendation that you use the API in `Bundle.package`. If I'm misunderstanding the problem (and I realize I'm coming in _very_ late!) please do reopen.
