### ISSUE TITLE
[SR-963] Support Code Coverage reports using `swift test`

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/swift-package-manager#5382]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-963      |
   |Radar             | None         |
   |Original Reporter | RamonN (JIRA User)      |
   |Type              | New Feature    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 2         |
   |Component/s       | Package Manager    |
   |Labels            | New Feature        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 587d8547aa713a398ee71af0c8933ec9

  </details>

**Issue Description:**

Support generating test coverage reports when running 'swift test'.

**Comment by dabrahams** [comment]
Isn't this sorta done?

**Comment by grynspan** [comment]
I just opened #7821. I'm going to roll this issue into that one as it covers a broader feature set.

**Comment by grynspan** [comment]
Duplicate of #7821
