### ISSUE TITLE
[SR-13405] SPM doesn't work with XCTest extensions.

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/swift-package-manager#6832]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13405      |
   |Radar             | rdar://problem/67363036         |
   |Original Reporter | Jessy (JIRA User)      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164963927-dfc4160b-43e9-4227-9cee-b303e74174e1.gz)

      
<details>
  <summary>Environment</summary>

Open the Workspace in Xcode 12. You'll get this:

ld: warning: Could not find or use auto-linked library 'XCTestSwiftSupport'

ld: warning: Could not find or use auto-linked framework 'XCTest'

Undefined symbols for architecture x86_64:

  "\_*swift_FORCE_LOAD*$\_XCTestSwiftSupport", referenced from:

      \_*swift_FORCE_LOAD*$*XCTestSwiftSupport*$\_TestExtensions in TestExtensions.o

ld: symbol(s) not found for architecture x86_64

clang: error: linker command failed with exit code 1 (use -v to see invocation)

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       |     |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: c3d5154fe0f075824590ffce499af6da

  </details>

**Issue Description:**

I had this question a few years ago, but I don't think I ever got it working with Carthage. I'd like to solve the problem now that SPM is the standard.

XCTest extensions should be usable within app test targets.

<https://stackoverflow.com/questions/38494490/how-do-you-create-public-extensions-in-a-shared-framework-for-xctest>

**Comment by grynspan** [comment]
The linked example should compile fine when included in a test target; since (on macOS in particular) XCTest is not available in production targets, it is not possible (nor will it reasonably become possible) for a non-test target to extend an XCTest type.

If I'm misunderstanding the issue, please reopen!
