### ISSUE TITLE
Unable to collect privacy manifest of static xcframework

### ISSUE THREAD

**Issue by tamwei** [swiftlang/swift-package-manager#7317]
### Description

The Package.swift of static xcframework is as follows:
```swift
import PackageDescription

let package = Package(
    name: "TestSDK",
    products: [
        // Products define the executables and libraries a package produces, and make them visible to other packages.
        .library(
            name: "TestSDK",
            targets: ["TestSDK"]),
    ],
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        // .package(url: /* package url */, from: "1.0.0"),
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages this package depends on.
        .binaryTarget(name: "TestSDK", path: "TestSDK.xcframework")

    ]
)

```

And the `PrivacyInfo.xcprivacy` is in `TestSDK.xcframework/ios-arm64/TestSDK.framework` directory.

----

Case 1: When integrating static TestSDK.xcframework through SwiftPM in the sample app, the Privacy Report I generated does not contain the privacy manifest of static TestSDK.xcframework.

Case 2: When I change the above static TestSDK.xcframework to a dynamic TestSDK.xcframework, the Privacy Report is correct

Case 3: When I am not using SwiftPM but manually integrating static `TestSDK.xcframework`, the privacy manifest collected is also correct.

The app.xcarchive of Case2 and Case3 has one more `Frameworks` folder than the app.xcarchive of Case1, which contains the PrivacyInfo.xcprivacy of TestSDK.xcframework

---
I want to specify the PrivacyInfo.xcprivacy of static xcframework in the Package.swift file, but `binaryTarget` does not support that.

**Comment by tamwei** [comment]
Using binaryTarget as a dependency of the target and adding PrivacyInfo.xcprivacy to the target's resources seems to solve this problem.

**Comment by iharkatkavets** [comment]
Few days ago Apple updated their documentation to cover static libs behaviour. 

> [Distribute your static library with a privacy manifest](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/adding_a_privacy_manifest_to_your_app_or_third-party_sdk#4336752)
> A static library is an archive of object files with the .a file extension. It doesn’t support resources such as the privacy manifest. If you currently distribute a static library as an SDK and want to update it to include a privacy manifest in Xcode, create a new static framework target that includes all your static library’s source files and resources, then add the privacy manifest to the target’s resource.
> If you don’t use Xcode to build your static library, create a static framework bundle for your static library manually, then add the privacy manifest to the bundle as a resource. For more information about framework bundle structure, see [Placing content in a bundle](https://developer.apple.com/documentation/bundleresources/placing_content_in_a_bundle). To identify the privacy manifest location in the static framework, see [Add a privacy manifest to your framework](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/adding_a_privacy_manifest_to_your_app_or_third-party_sdk#4336740).

The link [here](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/adding_a_privacy_manifest_to_your_app_or_third-party_sdk)
