### ISSUE TITLE
TestTarget unable to use build tool plugin to generate files

### ISSUE THREAD

**Issue by rauhul** [swiftlang/swift-package-manager#7597]
### Is it reproducible with SwiftPM command-line tools: `swift build`, `swift test`, `swift package` etc?

- [X] Confirmed reproduction steps with SwiftPM CLI.

### Description

swift-mmio fails to build with SwiftPM from main with the following error: "error: cannot find 'Banana' in scope" which is a type that should be generated by the `SVD2SwiftPlugin`.

### Expected behavior

Build succeeds (as is the case with 5.9 and 5.10)

### Actual behavior

Build fails with:
```swift
/code/Tests/SVD2SwiftPluginTests/SVD2SwiftTests.swift:17:5: error: cannot find 'Banana' in scope
15 |   // swift-format-ignore: AlwaysUseLowerCamelCase
16 |   func _do_not_run() {
17 |     Banana.timer1.cr.modify { _, _ in }
   |     `- error: cannot find 'Banana' in scope
18 |   }
```

### Steps to reproduce

`swift test` with swift-mmio @ `822f5e231dacb686030437ef18654d586a1575c6`

### Swift Package Manager version/commit hash

main

### Swift & OS version (output of `swift --version ; uname -a`)

```
Swift version 6.0-dev (LLVM cef183591317ec7, Swift 66e311074bff491)
Target: aarch64-unknown-linux-gnu
Linux b1edcdcd4c95 6.1.68 #1 SMP Thu May  2 02:50:09 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by xedin** [comment]
@rauhul I think this should be fixed by https://github.com/apple/swift-package-manager/pull/7593, would you might trying with that PR?

**Comment by xedin** [comment]
I triggered toolchain build with the changes @ https://ci.swift.org/job/swift-PR-toolchain-macos/1267/

**Comment by rauhul** [comment]
I'll try that toolchain when available!

**Comment by xedin** [comment]
Thank you!
