### ISSUE TITLE
Package.swift diagnostics on wrong line

### ISSUE THREAD

**Issue by award999** [swiftlang/swift-package-manager#7688]
### Is it reproducible with SwiftPM command-line tools: `swift build`, `swift test`, `swift package` etc?

- [X] Confirmed reproduction steps with SwiftPM CLI.

### Description

SwiftPM diagnostics for the Package.swift show up at a different line/column than SourceKit-LSP. In this picture the first diagnostics is from SourceKit and shows up at right place, but SwiftPM indicates the diagnostic is on the next line
<img width="596" alt="Screenshot 2024-06-19 at 1 12 31 PM" src="https://github.com/apple/swift-package-manager/assets/78549403/e1724a1a-1b26-4cd7-b959-28e1767d6cf3">

### Steps to reproduce

1. Set macOS platform to v13 in Package.swift
2. Set swift tool version to 5.6: `// swift-tools-version: 5.6`
3. Save file and `swift package resolve`

Notice output:
<img width="614" alt="Screenshot 2024-06-19 at 2 01 58 PM" src="https://github.com/apple/swift-package-manager/assets/78549403/c255973c-3042-4281-8a9b-2221f6f023bf">

As you can see in the picture above the line was line 9, so line is off by one, but the column seems right

### Swift & OS version (output of `swift --version ; uname -a`)

swift-driver version: 1.110 Apple Swift version 6.0 (swiftlang-6.0.0.4.52 clang-1600.0.21.1.3)
Target: arm64-apple-macosx15.0

**Comment by MaxDesiatov** [comment]
Is this reproducible for errors in other files too, or only `Package.swift`?

**Comment by award999** [comment]
Only seems to be this specific case in Package.swift, for example doing something like this put on the right line (22 like I'd expect):
<img width="614" alt="Screenshot 2024-06-19 at 3 42 34 PM" src="https://github.com/apple/swift-package-manager/assets/78549403/b0428865-fc5c-4738-8ff3-7ead813b916c">

All diagnostics from `swiftc` seem correct
