### ISSUE TITLE
`swift package add-dependency-to-target` command

### ISSUE THREAD

**Issue by MahdiBM** [swiftlang/swift-package-manager#7758]
### Description

Would be nice if there was also a command to add a dependency to a target of a package.

### Expected behavior

A command like `swift package add-dependency-to-target` would be optimal (with a better name maybe).
It can work like:
```
swift package add-dependency-to-target --target MyAppTarget --name DiscordHTTP --package DiscordBM
```

### Actual behavior

No such commands.

### Steps to reproduce

Feature Request - No steps to reproduce.

### Swift Package Manager version/commit hash

`Swift Package Manager - Swift 6.0.0-dev`

### Swift & OS version (output of `swift --version && uname -a`)

```bash
swift-driver version: 1.109.2 Apple Swift version 6.0 (swiftlang-6.0.0.3.300 clang-1600.0.20.10)
Target: arm64-apple-macosx15.0
Darwin ---.local 24.0.0 Darwin Kernel Version 24.0.0: ---; root:xnu-11215.0.115.501.3~1/RELEASE_ARM64_T6000 arm64
```

**Comment by bripeticca** [comment]
Hello @MahdiBM! Thanks for publishing this feature request - I was taking a look at the current available commands for SwiftPM and noticed the following existing command:

```bash
swift package add-target-dependency --help
OVERVIEW: Add a new target dependency to the manifest

USAGE: swift package add-target-dependency <dependency-name> <target-name> [--package <package>]

ARGUMENTS:
  <dependency-name>       The name of the new dependency
  <target-name>           The name of the target to update

OPTIONS:
  --package <package>     The package in which the dependency resides
  --version               Show the version.
  -h, -help, --help       Show help information.
```

Is this the behaviour you were looking for?

**Comment by MahdiBM** [comment]
Yes. Apparently it got added at some point. I just tested with the latest main snapshot and it does work as expected.
