### ISSUE TITLE
[Swift-Testing] Package addition is required on Linux CLI, but not on macOS

### ISSUE THREAD

**Issue by MahdiBM** [swiftlang/swift-package-manager#7763]
### Is it reproducible with SwiftPM command-line tools: `swift build`, `swift test`, `swift package` etc?

- [X] Confirmed reproduction steps with SwiftPM CLI. The description text _must_ include reproduction steps with either of command-line SwiftPM commands, `swift build`, `swift test`, `swift package` etc.

### Description

On linux, you need to add `swift-testing` as a dependency, but on macOS, you don't need to.

### Expected behavior

Unified behavior on macOS and Linux.

### Actual behavior

On macOS, this successfully runs the tests:
```bash
~ swift testing --enable-swift-testing
```
On Linux:
```bash
~ swift testing --enable-swift-testing
/__w/my-package/my-package/Tests/MyTests/MyThingTests.swift:1:8: error: no such module 'Testing'
  1 | import Testing
    |        `- error: no such module 'Testing'
```

### Steps to reproduce

Described above.

### Swift Package Manager version/commit hash

Bundled with Xcode 16 beta 2.

### Swift & OS version (output of `swift --version ; uname -a`)

```bash
swift-driver version: 1.110 Apple Swift version 6.0 (swiftlang-6.0.0.4.52 clang-1600.0.21.1.3)
Target: arm64-apple-macosx15.0
Darwin ---.local 24.0.0 Darwin Kernel Version 24.0.0: ---; root:xnu-11215.0.115.501.3~1/RELEASE_ARM64_T6000 arm64
```

**Comment by MahdiBM** [comment]
Related: https://github.com/swiftlang/swift/issues/75037
cc @grynspan

**Comment by grynspan** [comment]
We haven't added Swift Testing to the open source toolchain yet. This is not a Swift issue.
