### ISSUE TITLE
Building main branch fails with swift-argument-parser dependency error

### ISSUE THREAD

**Issue by dempseyatgithub** [swiftlang/swift-package-manager#7776]
### Is it reproducible with SwiftPM command-line tools: `swift build`, `swift test`, `swift package` etc?

- [X] Confirmed reproduction steps with SwiftPM CLI. The description text _must_ include reproduction steps with either of command-line SwiftPM commands, `swift build`, `swift test`, `swift package` etc.

### Description

Trying to build the main branch locally fails with the following dependency error:

"error: Dependencies could not be resolved because root depends on 'swift-argument-parser' 1.4.0..<1.5.0 and 'swift-driver' depends on 'swift-argument-parser' 1.2.2..<1.3.0."

This is likely a result of #7450.

### Steps to reproduce

1. Pull main branch from repository
2. Attempt to build with `swift build`

### Swift Package Manager version/commit hash

125b3eb7d85f9e47cc5f8e66041e848cfc8ad066

### Swift & OS version (output of `swift --version ; uname -a`)

swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-macosx14.0
Darwin jdmbp.local 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:17:33 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6031 arm64

swift-driver version: 1.111.2 Apple Swift version 6.0 (swiftlang-6.0.0.5.15 clang-1600.0.22.6)
Target: arm64-apple-macosx14.0
Darwin jdmbp.local 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:17:33 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6031 arm64

**Comment by MaxDesiatov** [comment]
This is not reproducible for me locally. You likely have a stale `swift-driver` checkout that doesn't include https://github.com/swiftlang/swift-driver/commit/5f8cfdff80aec356ea2a4f3491e3dabba9645821.
