### ISSUE TITLE
Invalid build setting `swiftLanguageVersion`

### ISSUE THREAD

**Issue by glbrntt** [swiftlang/swift-package-manager#7823]
### Is it reproducible with SwiftPM command-line tools: `swift build`, `swift test`, `swift package` etc?

- [X] Confirmed reproduction steps with SwiftPM CLI. The description text _must_ include reproduction steps with either of command-line SwiftPM commands, `swift build`, `swift test`, `swift package` etc.

### Description

Swift 6 nightly builds using `swiftLanguageVersion` now fail with:

```
InternalError(description: "Internal error. Please file a bug at https://github.com/swiftlang/swift-package-manager/issues with this info. invalid build setting swiftLanguageVersion"
```

This makes sense as it's now been renamed to `swiftLanguageMode` (https://github.com/swiftlang/swift-package-manager/pull/7620).

### Expected behavior

Build should still compile but warn about the deprecated setting.

Presumably [this code](https://github.com/dempseyatgithub/swift-package-manager/blob/83c96a147b31d5d5bfafd5078a10a04e16163f22/Sources/PackageDescription/BuildSettings.swift#L419-L426) should return a setting with name "swiftLanguageMode" rather than "swiftLanguageVersion".

### Actual behavior

Build fails with an error

```
InternalError(description: "Internal error. Please file a bug at https://github.com/swiftlang/swift-package-manager/issues with this info. invalid build setting swiftLanguageVersion"
```

**Comment by MaxDesiatov** [comment]
@glbrntt can you provide a sample package the reproduces the issue? Thanks!

**Comment by glbrntt** [comment]
[Repro.zip](https://github.com/user-attachments/files/16379952/Repro.zip)

This was on `swiftlang/swift:nightly-6.0-jammy` at `sha256:4624a3c7404f479e55d69dc5e41f94e399cb0c11f291f81689d81e593b409610`

**Comment by glbrntt** [comment]
I think that's fine, but in the PR the setting was deprecated, which makes sense as it gives early adopters a way to find out what to use next. 

However it still causes builds to fail because the old (deprecated) setting is now invalid so we lose the 'gracefulness' of deprecating the setting. There's also a mismatch between nightly-6.0, nightly-main, and released toolchains for macOS which means its hard for libraries to develop for both platforms (at the moment).

**Comment by MaxDesiatov** [comment]
I don't think that gracefulness can be guaranteed in development snapshots. The mismatch will disappear as soon the change is propagated to different builds.

**Comment by xedin** [comment]
I think, this is just a bug, deprecated `swiftLangaugeVersion` should produce a `swiftLanguageMode` setting. This is something we missed during review, I'll fix it.

**Comment by dempseyatgithub** [comment]
> I think, this is just a bug, deprecated `swiftLangaugeVersion` should produce a `swiftLanguageMode` setting. This is something we missed during review, I'll fix it.

Thank you @xedin.
