### ISSUE TITLE
My custom  SPM force me to use Rosetta destinations

### ISSUE THREAD

**Issue by a7maad-ayman** [swiftlang/swift-package-manager#7890]
### Is it reproducible with SwiftPM command-line tools: `swift build`, `swift test`, `swift package` etc?

- [X] Confirmed reproduction steps with SwiftPM CLI. The description text _must_ include reproduction steps with either of command-line SwiftPM commands, `swift build`, `swift test`, `swift package` etc.

### Description

Hi there,

When I add my custom SPM to my project, it doesn't run and gives me the following error:

![Error Screenshot](https://github.com/user-attachments/assets/4d57dab8-b5fc-4f2a-aec4-04c0c8f3e4cd)

It also forces me to use Rosetta. How can I resolve this?

### Expected behavior

It should be universal and run for `arm64` too.

### Actual behavior

When I add my custom SPM to my project, it doesn't run and It also forces me to use Rosetta. 

### Swift Package Manager version/commit hash

 5.10

### Swift & OS version (output of `swift --version ; uname -a`)

`xcode` : 15 
`swift`:   5.10
`swift-tools-version` : 5.8

**Comment by dschaefer2** [comment]
Do you have steps to reproduce with swift command line tools? It looks like you were using Xcode?

**Comment by a7maad-ayman** [comment]
What difference does it make? We recently created a lot of SPMs in both ways. How does the way of creating them affect anything?

**Comment by dschaefer2** [comment]
Swift package manager, i.e. the command line tools, does not have support for building universal binaries at this time.

**Comment by dschaefer2** [comment]
Appears to be Xcode related. Please report your issue here. https://developer.apple.com/bug-reporting/
