### ISSUE TITLE
Host build are "sandboxed" by target triple

### ISSUE THREAD

**Issue by rauhul** [swiftlang/swift-package-manager#7899]
### Is it reproducible with SwiftPM command-line tools: `swift build`, `swift test`, `swift package` etc?

- [X] Confirmed reproduction steps with SwiftPM CLI. The description text _must_ include reproduction steps with either of command-line SwiftPM commands, `swift build`, `swift test`, `swift package` etc.

### Description

When switching target triples from say `arm64-apple-macosx15-macho` to `armv7em-apple-none-macho`, SwiftPM rebuilds all host content. I think is because "tools/host" content is not shared between target triples. You can see this by looking in the `.build` directory and seeing that each target directory contains their own `-tools` directory built for the host.

See output of `➜  swift-mmio git:(main) ✗ fd '.*-tool' .build/aarch64-unknown-linux-gnu/debug .build/arm64-apple-macosx/debug | sort | pbcopy`

[files.txt](https://github.com/user-attachments/files/16680950/files.txt)

**Comment by dschaefer2** [comment]
I think you're seeing the same issue over and over again. The host and destination builds are separate but generate into the same directories. That appears to be making a mess.

The question on my mind now is why aren't they one build?

**Comment by dschaefer2** [comment]
Deleted earlier poorly thought out reply.

Why do you have output for linux?

**Comment by rauhul** [comment]
> Why do you have output for linux?

was cross compiling for linux, but could've easily been an embedded triple instead

**Comment by dschaefer2** [comment]
> > Why do you have output for linux?
> 
> was cross compiling for linux, but could've easily been an embedded triple instead

Ah, it looked like another host build with docker or something. Makes sense.

Question is, why do target output directories have tools at all. They should only be on the host.

**Comment by dschaefer2** [comment]
Does your armv7em directory have -tools things? I wonder if it considers linux a host...

**Comment by rauhul** [comment]
Hmm I can't reproduce this in a clean area. I'm gonna close it and reopen with a concrete repro if it does.

<img width="1631" alt="Screenshot 2024-08-20 at 7 59 05 PM" src="https://github.com/user-attachments/assets/25630165-6d9c-4a82-8bc5-a74c6624e306">

**Comment by dschaefer2** [comment]
Thanks!
