### ISSUE TITLE
Swift package compile times are 10-20 times worse on Windows than on Linux

### ISSUE THREAD

**Issue by silverhammermba** [swiftlang/swift-package-manager#7943]
### Description

Building the exact same Swift package on the same computer but using Windows takes orders of magnitude longer for both clean and incremental builds than doing it on Linux.

### Reproduction

I've been trying to build this Swift package: https://github.com/migueldeicaza/SwiftGodot/. For future reference, I'm building tag 0.40.0

I reported this issue to the maintainer of that package and he insists the slowdown is purely up to the Swift compiler to fix: https://github.com/migueldeicaza/SwiftGodot/issues/299#issuecomment-1963062462

### Expected behavior

The above package build on Linux takes 83 seconds for a clean build and 3 seconds for an incremental build (after making trivial changes).

In Windows 10 it takes **19 minutes** for a clean build and **13 minutes** for an incremental build. This makes the package all but unusable on Windows. Comparing the incremental builds (which are the most important, in my opinion), that's over 240 times slower than on Linux.

### Environment

Swift version 5.9.2 (swift-5.9.2-RELEASE)
Target: x86_64-unknown-windows-msvc

### Additional information

I'm up for profiling this to figure out exactly where the slowdown is but I don't know where to get started with that.

**Comment by jakepetroules** [comment]
This issue is resolved by swiftlang/swift-llbuild#937
