### ISSUE TITLE
Error creating symbolic link during `swift run` on Windows

### ISSUE THREAD

**Issue by timsneath** [swiftlang/swift-package-manager#7965]
### Description

On a Windows 11 machine, either `swift build` or `swift run` work the first time, but on repeated execution they report an error:

> Build of product 'win32test' complete! (0.10s)
> warning: unable to create symbolic link at C:\src\scratch\.build\debug: Error Domain=NSCocoaErrorDomain Code=516 "A file with the same name already exists."
> 

![image](https://github.com/user-attachments/assets/ddef293b-a44c-488b-8df0-9b8008bbb53e)

### Reproduction

Run:

```text
swift package init --type executable --name win32test
swift build
swift run
```

### Expected behavior

Expected that repeated `swift run` invocations are idempotent.

### Environment

Swift version 6.0-dev (LLVM c3efe9282719c35, Swift b163fed2b3101e0)
Target: aarch64-unknown-windows-msvc

**Comment by dschaefer2** [comment]
From what I've seen so far these links aren't really used. You can access the build results using the toolchain triple and then debug/release.

But yes, disconcerting. It's on my list of Windows bugs to look at. Unfortunately there are a few more ahead of it.



> I have the same problem with release version of Swift 6.0 toolchain. Also it creates symlinks without "list content" permission.

That's a good clue. Thanks!

**Comment by dschaefer2** [comment]
Digging into this now. This might be a bug in how swift-foundation is creating the symlink on Windows.

**Comment by dschaefer2** [comment]
Yup, FileManager is incorrectly creating the link. Details here: https://github.com/apple/swift-foundation/issues/928

I'll keep this open until we have it resolved. I can link it absolute but then it wouldn't allow the directory to be moved which might be OK, but let's see how that issue progresses.

**Comment by swat199538** [comment]
me too

**Comment by dschaefer2** [comment]
Sounds like a fix is on the way to swift-foundation. I'll wait for that and make sure it fixes this.

**Comment by dschaefer2** [comment]
The fix is in. Tested with the Sept 24 CI build. Best wait until an official development snapshot is released to try it.
