### ISSUE TITLE
`swift build` fails to build SwiftPM

### ISSUE THREAD

**Issue by valeriyvan** [swiftlang/swift-package-manager#7976]
### Is it reproducible with SwiftPM command-line tools: `swift build`, `swift test`, `swift package` etc?

- [X] Confirmed reproduction steps with SwiftPM CLI. The description text _must_ include reproduction steps with either of command-line SwiftPM commands, `swift build`, `swift test`, `swift package` etc.

### Description

`CONTRIBUTING.md` says that with the SwiftPM code cloned it could be build with running `swift build`.

Running `swift build` fails with error `error: Dependencies could not be resolved because root depends on 'swift-argument-parser' 1.4.0..<1.5.0 and 'swift-driver' depends on 'swift-argument-parser' 1.0.1..<1.1.0.`.

This part of fixing `Package.swift` before building is not reflected anywhere in the documentation.

After fixing `Package.swift` with setting  'swift-argument-parser' to version 1.0.3, the latest before 1.1.0, `swift build` fails with multiple compile errors.

### Expected behavior

I expect `swift build` recommended for building in the documentation to build latest `main` branch successfully. If `swift build` couldn't or shouldn't be used for building SwiftPM, documentation should be fixed.

### Actual behavior

`swift build` fails

### Steps to reproduce

1. clone this repo or update `main`
2. run `swift build` inside swiftpm folder

### Swift Package Manager version/commit hash

da65429043cb0a5151bdd5e9666df770dfbc72a5

### Swift & OS version (output of `swift --version ; uname -a`)

```
swift --version ; uname -a 
swift-driver version: 1.115 Apple Swift version 6.0 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)
Target: arm64-apple-macosx14.0
Darwin VV-LIN-MBP.local 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:21 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T8103 arm64
```

**Comment by dschaefer2** [comment]
Could you try a `swift package update`? I wonder if you have old versions of the dependencies in your global cache.

**Comment by valeriyvan** [comment]
> Could you try a `swift package update`? I wonder if you have old versions of the dependencies in your global cache.

That did the trick! After `swift package update` both `swift build` and building inside Xcode succeed. Thank you very much!
