### ISSUE TITLE
Swift Testing not able to run test in debug mode, due to `get-task-allow` entitlement.

### ISSUE THREAD

**Issue by zaneenders** [swiftlang/swift-package-manager#7994]
**Describe the bug**
Swift Testing not able to run test in debug mode, due to get-task-allow entitlement.

**To Reproduce**
Using swift 6.0 (Included in MacOS)
```
mkdir Test
cd Test
swift package init
```
Open up the <package-name>Tests.swift file
```swift
import Testing
@testable import Test

@Test func example() async throws {
    #expect(true)
}
```
Then right-click on the test and click "Debug Test". This will take a second to run then throw an error telling you to check the console.

which displays this error for the kernel process.
```
macOSTaskPolicy: (com.apple.debugserver) may not get the task control port of (swiftpm-testing-) (pid: 36379): (swiftpm-testing-) is hardened, (swiftpm-testing-) doesn't have get-task-allow, (com.apple.debugserver) is a declared debugger(com.apple.debugserver) is not a declared read-only debugger
```

**Expected behavior**
Be able to set a break point and debug test.

**Environment**
 - OS: 15.0 (24A335)
 - Swift version: swift-driver version: 1.115 Apple Swift version 6.0 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)
Target: arm64-apple-macosx15.0
 - Visual Studio Code version: Version: 1.93.1 (Universal)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
 - vscode-swift version: 1.11.1

Thank you for making such a great extension.

**Comment by plemarquand** [comment]
Some more context:
The missing entitlement is `com.apple.security.get-task-allow`
The target binary is `swiftpm-testing-helper` (this appears truncated in the error message)

**Comment by plemarquand** [comment]
Synced to Apple’s issue tracker as rdar://136527648

**Comment by zaneenders** [comment]
Thank you!

**Comment by grynspan** [comment]
Thanks for filing! As this is an issue specifically with Apple's fork of Swift, I'm closing this issue. That doesn't mean we're not working on it or it won't be resolved or anything like that—just that there's no further work needed on the open source side. Apple is tracking the issue in their internal issue tracker.

If I've missed something, please comment and I'll reopen.

**Comment by zaneenders** [comment]
This might also be related when running "Run Tests with Coverage"

`LLVM Profile Error: Failed to write file "default.profraw": Operation not permitted`


``` 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift test --enable-code-coverage --enable-swift-testing --event-stream-version 0 --event-stream-output-path /var/folders/zr/gx_s3hh559qggps3wlqn_xvh0000gn/T/vscodemkfifo-1728963832535 --disable-xctest --filter ParserTests\.* -Xswiftc -diagnostic-style=llvm
```
