### ISSUE TITLE
Incorrect products provided to command plugin when a local macro target that imports SwiftSyntaxMacros is imported by a product

### ISSUE THREAD

**Issue by JacobHearst** [swiftlang/swift-package-manager#8082]
### Is it reproducible with SwiftPM command-line tools: `swift build`, `swift test`, `swift package` etc?

- [X] Confirmed reproduction steps with SwiftPM CLI. The description text _must_ include reproduction steps with either of command-line SwiftPM commands, `swift build`, `swift test`, `swift package` etc.

### Description

When enumerating the products in a package from a command plugin, the listed products are incorrect when one of the products imports a macro which imports `SwiftSyntaxMacros`.

Interestingly, if you duplicate the macro importing product and change the name, the second product is correctly included ([example](https://github.com/JacobHearst/SPM-Bug-SamplePackage/commit/dbd9c0cb13973f4416c495343fe563e149bef5d1)). Order does appear to matter as putting the second product first in the `products` array results in its exclusion ([example](https://github.com/JacobHearst/SPM-Bug-SamplePackage/commit/804acb65c736ffae52dfa20accc26d89cc3dcb1c))

### Expected behavior

`products` contains all the package's products

### Actual behavior

`products` contains `SwiftSyntaxMacros` and is missing the first product in the package's `products` array

### Steps to reproduce

1. Clone [this sample repo](https://github.com/JacobHearst/SPM-Bug-SamplePackage)
2. Run `swift package plugin dump-products`
3. Verify `["SwiftSyntaxMacros"]` is printed
4. Comment out the `SwiftSyntaxMacros` dependency on line 34 of `Package.swift` ([example](https://github.com/JacobHearst/SPM-Bug-SamplePackage/commit/cad998f2b2038f3c79af6e29500cb93e95cb1fcf))
5. Run `swift package plugin dump-products`
6. Verify `["SamplePackage"]` is printed
7. Uncomment the `SwiftSyntaxMacros` dependency
8. Comment out the `SampleMacro` dependency on line 18 of `Package.swift` ([example](https://github.com/JacobHearst/SPM-Bug-SamplePackage/commit/9f5e58933cba45bae0ce38f10756d09b21dcb227))
9. Run `swift package plugin dump-products`
10. Verify `["SamplePackage"]` is printed

### Swift Package Manager version/commit hash

```
$ swift package --version
Swift Package Manager - Swift 6.0.0-dev
```

### Swift & OS version (output of `swift --version ; uname -a`)

```
$ swift --version 
swift-driver version: 1.115 Apple Swift version 6.0 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)
Target: arm64-apple-macosx15.0

$ uname -a
Darwin JacBook-Pro.local 24.0.0 Darwin Kernel Version 24.0.0: Tue Sep 24 23:39:07 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T6000 arm64
```

**Comment by JacobHearst** [comment]
This actually looks like it was fixed sometime between `release/6.0.2` and `main` based on local experimentation, If I can find what exactly fixed things, is there a way to tell when the fix will be released?

**Comment by dschaefer2** [comment]
Main will become 6.1 so whenever that goes out.

**Comment by JacobHearst** [comment]
Amazing, thank you @dschaefer2. I'll close this issue since it's just waiting on release
