### ISSUE TITLE
Update macOS self-hosted pipeline to the nightly toolchain

### ISSUE THREAD

**Issue by bkhouri** [swiftlang/swift-package-manager#8137]
### Is it reproducible with SwiftPM command-line tools: `swift build`, `swift test`, `swift package` etc?

- [X] Confirmed reproduction steps with SwiftPM CLI. The description text _must_ include reproduction steps with either of command-line SwiftPM commands, `swift build`, `swift test`, `swift package` etc.

### Description

The macOS self-hosted pipeline is running Swift 5.9.2.  This prevents the use of Swift Testing, and is currently blocking, at a minimum, the following PRs (which are currently marked as draft pending resolution if this issue):

- https://github.com/swiftlang/swift-package-manager/pull/8100
- https://github.com/swiftlang/swift-package-manager/pull/8099
- https://github.com/swiftlang/swift-package-manager/pull/8093
- https://github.com/swiftlang/swift-package-manager/pull/8092

It would be ideal to update the macOS self-hosted pipeline toolchain version such that it uses the same version across all pipelines.

### Expected behavior

A toolchain version that supports Swift Testing is in use by all pipelines.

Accessing the last successful build will show Swift 6.x in use.
https://ci.swift.org/job/swift-package-manager-with-xcode-self-hosted-PR-osx/lastSuccessfulBuild/execution/node/43/log/

### Actual behavior

The self-hosted macOS pipeline is still using 5.9.2. 

https://ci.swift.org/job/swift-package-manager-with-xcode-self-hosted-PR-osx/4562/execution/node/43/log/

### Steps to reproduce

Open the last successful build

https://ci.swift.org/job/swift-package-manager-with-xcode-self-hosted-PR-osx/lastSuccessfulBuild/execution/node/43/log/

### Swift Package Manager version/commit hash

N/A

### Swift & OS version (output of `swift --version ; uname -a`)

N/A

**Comment by shahmishal** [comment]
Created a new pull request job to support nightly toolchain testing. 

```
@swift-ci Please test nightly self hosted
```

**Comment by bkhouri** [comment]
The self-hosted macOS pipeline using the nightly toolchain is now a required pipeline.

<img width="887" alt="Screenshot 2024-12-19 at 9 32 23 PM" src="https://github.com/user-attachments/assets/33b1e114-4a7b-4a95-bfa2-188309a69ce5" />

Closing this issue as it has been fixed.
